version: '3.5'

services:

  pnd-model-app:
    image: pndwebprod:latest
    ports:
      - 5006:5000
    environment:
      - APP_NAME=prime numbers predictor
      - PYTHONUNBUFFERED=1
      - APP_SETTINGS=project.config.server_config.TestingConfig
      - STARTUP_RETRAIN= False
    entrypoint: "python manage.py run -h 0.0.0.0"
